### ISSUE TITLE
PowerDnsProvider does call to PowerDNS server for version information

### ISSUE THREAD

**Issue by fjaeckel** [octodns/octodns-powerdns#39]
As part of the new `mode_of_operation` octodns-powerdns needs to validate wether the underlying PowerDNS supports the mode.
https://github.com/octodns/octodns-powerdns/blob/42f3de5fcf908dda73ff8e22da63be42f97aa24d/octodns_powerdns/__init__.py#L96

`octodns-powerdns` does that via calling to PowerDNS and asking for its version: 
https://github.com/octodns/octodns-powerdns/blob/42f3de5fcf908dda73ff8e22da63be42f97aa24d/octodns_powerdns/__init__.py#L283-L303

This creates issues in CI, when `octodns-validate` doesn't have the production credentials, which obviously it shouldn't.

We went around the issue, by using our own PowerDnsProvider which instantiates `octodns-powerdns` and then we override the `mode_of_operation` setter.
 https://github.com/octodns/octodns-powerdns/blob/42f3de5fcf908dda73ff8e22da63be42f97aa24d/octodns_powerdns/__init__.py#L335-L345

Its not the nicest solution and maybe there is a better way out, by either providing `PowerDnsProvider` with the version number, so it doesn't have to call PowerDNS or the ability to disable the call for CI.

A gist of where it failed in CI:
https://gist.github.com/fjaeckel/6500b24b822492916cf2b58aea1bedc9#file-gistfile1-txt

**Comment by ross** [comment]
> by either providing `PowerDnsProvider` with the version number, so it doesn't have to call PowerDNS or the ability to disable the call for CI.

Either of those may work. The other option that came to mind would be to defer/delay the call until the if/when the `mode_of_operation` was specifically required. Presumably/hopefully `octodns-validate` could run without needing that answered.
