### ISSUE TITLE
Add support for 'LUA' records in PowerDNS

### ISSUE THREAD

**Issue by splk3** [octodns/octodns-powerdns#7]
PowerDNS Authoritative Server 4.3.0 added a new "LUA" record type that allows lua-scripted answers to be returned as answers to a DNS query.  For example, a LUA record could respond to an A record request by doing a health check to a server and then returning the properly formatted IP address.

The "LUA" record also is used to implement Geo/Dynamic record types, including multiple health check mechanisms, so the README table can be updated to "Yes" for those features in OctoDNS record type(s) support.

While looking through the [PowerDNS Provider](https://github.com/github/octodns/blob/master/octodns/provider/powerdns.py), it looks like the new record type can be added pretty easily by configuring the LUA record type as another quoted type, leaving the responsibility for format and correctness to the user.

Adding the following should be sufficient (or at least a start):

(not sure if below only update docs or there are other effects)

```python
SUPPORTS_GEO = True
SUPPORTS_DYNAMIC = True 
    SUPPORTS = set(('A', 'AAAA', 'ALIAS', 'CAA', 'CNAME', 'LUA', 'MX', 'NAPTR', 'NS',
                    'PTR', 'SPF', 'SSHFP', 'SRV', 'TXT'))

_data_for_LUA = data_for_quoted
_records_for_LUA = _records_for_quoted
```

If there is more required, I can look into that, as well.  I'm happy to try and do a pull request, but I have very little python experience and will have to start from scratch getting the development environment set up for testing.

Thanks in advance and having great success with OctoDNS with PowerDNS already!

**Comment by sevencastles** [comment]
@ross is there any plan to add custom types for providers? LUA records are quite an interesting feature

**Comment by ross** [comment]
Filed https://github.com/PowerDNS/pdns/issues/9310 a while back as i couldn't figure out how to get LUA records created via the API. I could do it in SQL. That's kind of blocking any movement in this area.
